### ISSUE TITLE
Failed output Pre-commit Hook

### ISSUE THREAD

**Issue by ehontoria** [executablebooks/mdformat#131]
**Describe the bug**

When running `mdformat` as a pre-commit hook whenever `mdformat` fails there is a secondary error that happens and does not show the error output for `mdformat`.

Pre-commit setup:
```
repos:
-    repo: https://github.com/executablebooks/mdformat
     rev: 0.5.6
     hooks:
         -    id: mdformat
              args: [--check]
```

Error when running with `pre-commit`:
```
Traceback (most recent call last):
  File "/Users/emily.hontoria/.cache/pre-commit/reponc4o4tlo/py_env-python3.8/bin/mdformat", line 8, in <module>
    sys.exit(run())
  File "/Users/emily.hontoria/.cache/pre-commit/reponc4o4tlo/py_env-python3.8/lib/python3.8/site-packages/mdformat/__main__.py", line 8, in run
    exit_code = mdformat._cli.run(sys.argv[1:])
  File "/Users/emily.hontoria/.cache/pre-commit/reponc4o4tlo/py_env-python3.8/lib/python3.8/site-packages/mdformat/_cli.py", line 69, in run
    print_error(f'File "{path_str}" is not formatted.')
  File "/Users/emily.hontoria/.cache/pre-commit/reponc4o4tlo/py_env-python3.8/lib/python3.8/site-packages/mdformat/_cli.py", line 165, in print_error
    print_paragraphs(paragraphs)
  File "/Users/emily.hontoria/.cache/pre-commit/reponc4o4tlo/py_env-python3.8/lib/python3.8/site-packages/mdformat/_cli.py", line 157, in print_paragraphs
    sys.stderr.write(wrap_paragraphs(paragraphs))
  File "/Users/emily.hontoria/.cache/pre-commit/reponc4o4tlo/py_env-python3.8/lib/python3.8/site-packages/mdformat/_cli.py", line 179, in wrap_paragraphs
    return "\n\n".join(wrapper.fill(p) for p in paragraphs) + "\n"
  File "/Users/emily.hontoria/.cache/pre-commit/reponc4o4tlo/py_env-python3.8/lib/python3.8/site-packages/mdformat/_cli.py", line 179, in <genexpr>
    return "\n\n".join(wrapper.fill(p) for p in paragraphs) + "\n"
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/textwrap.py", line 363, in fill
    return "\n".join(self.wrap(text))
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width 0 (must be > 0)
```

"Error" when running normally with `mdformat`:
```
Error: File "blah.md" is
not formatted.
```

**To Reproduce**

1. Intentionally create a file that will fail `mdformat`.
2. Add pre-commit to the environment with the above pre-commit setup.
3. Run `pre-commit run --all-files` to produce an "error" on file not formatted.
4. Observe above `ValueError`.

**Expected behavior**

The error message from mdformat is included instead of the `ValueError`.
Namely I would prefer:
```
Error: File "blah.md" is
not formatted.
```

Instead of:
```
Traceback (most recent call last):
  File "/Users/emily.hontoria/.cache/pre-commit/reponc4o4tlo/py_env-python3.8/bin/mdformat", line 8, in <module>
    sys.exit(run())
  File "/Users/emily.hontoria/.cache/pre-commit/reponc4o4tlo/py_env-python3.8/lib/python3.8/site-packages/mdformat/__main__.py", line 8, in run
    exit_code = mdformat._cli.run(sys.argv[1:])
  File "/Users/emily.hontoria/.cache/pre-commit/reponc4o4tlo/py_env-python3.8/lib/python3.8/site-packages/mdformat/_cli.py", line 69, in run
    print_error(f'File "{path_str}" is not formatted.')
  File "/Users/emily.hontoria/.cache/pre-commit/reponc4o4tlo/py_env-python3.8/lib/python3.8/site-packages/mdformat/_cli.py", line 165, in print_error
    print_paragraphs(paragraphs)
  File "/Users/emily.hontoria/.cache/pre-commit/reponc4o4tlo/py_env-python3.8/lib/python3.8/site-packages/mdformat/_cli.py", line 157, in print_paragraphs
    sys.stderr.write(wrap_paragraphs(paragraphs))
  File "/Users/emily.hontoria/.cache/pre-commit/reponc4o4tlo/py_env-python3.8/lib/python3.8/site-packages/mdformat/_cli.py", line 179, in wrap_paragraphs
    return "\n\n".join(wrapper.fill(p) for p in paragraphs) + "\n"
  File "/Users/emily.hontoria/.cache/pre-commit/reponc4o4tlo/py_env-python3.8/lib/python3.8/site-packages/mdformat/_cli.py", line 179, in <genexpr>
    return "\n\n".join(wrapper.fill(p) for p in paragraphs) + "\n"
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/textwrap.py", line 363, in fill
    return "\n".join(self.wrap(text))
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width 0 (must be > 0)
```

**Environment**

- Python Version [e.g. 3.7.1]: 3.8.4
- Package version of mdformat: 0.5.6
- Package version of pre-commit: 2.10.1
- Operating System: MacOS Catalina 10.15.4

**Additional context**

No additional context.

**Comment by hukkinj1** [comment]
Thanks for the issue! :smile_cat:  I can reproduce, this is indeed a bug.

The environment where pre-commit operates seems to report a terminal window width of 0 and that confuses mdformat when formatting standard error output.

Version 0.5.7 will fix this and it will be on PyPI in just a minute!
